services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../provisioning:/etc/grafana/provisioning
      - ../grafana/data:/var/lib/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
