{
 "title": "System Monitoring",
 "time": { "from": "2024-08-02T15:54:50.196Z", "to": "2024-08-09T18:34:50.196Z" },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "percent_cpu", "legendFormat": "CPU Usage (%)" },
    { "expr": "percent_cpu_process_usage", "legendFormat": "CPU Usage by Process (%)" }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_virtual_memory_avail", "legendFormat": "Total VM Available" },
    { "expr": "virtual_memory_used", "legendFormat": "Total VM Used" },
    { "expr": "virtual_memory_process", "legendFormat": "VM Used By Project" }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_ram", "legendFormat": "Total RAM Avail" },
    { "expr": "ram_used", "legendFormat": "Total RAM Used" },
    { "expr": "ram_process", "legendFormat": "RAM Used by Project" }
   ]
  }
 ]
}